// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/inter-hubly/pilot/domain/entity"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetCampaignById mocks base method.
func (m *MockRepository) GetCampaignById(ctx context.Context, campaignId string) (*entity.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignById", ctx, campaignId)
	ret0, _ := ret[0].(*entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignById indicates an expected call of GetCampaignById.
func (mr *MockRepositoryMockRecorder) GetCampaignById(ctx, campaignId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignById", reflect.TypeOf((*MockRepository)(nil).GetCampaignById), ctx, campaignId)
}

// GetCampaignsByIds mocks base method.
func (m *MockRepository) GetCampaignsByIds(ctx context.Context, campaignId ...string) ([]entity.Campaign, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range campaignId {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCampaignsByIds", varargs...)
	ret0, _ := ret[0].([]entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignsByIds indicates an expected call of GetCampaignsByIds.
func (mr *MockRepositoryMockRecorder) GetCampaignsByIds(ctx interface{}, campaignId ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, campaignId...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignsByIds", reflect.TypeOf((*MockRepository)(nil).GetCampaignsByIds), varargs...)
}

// GetCampaignsTemplateById mocks base method.
func (m *MockRepository) GetCampaignsTemplateById(ctx context.Context, campaignId []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignsTemplateById", ctx, campaignId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignsTemplateById indicates an expected call of GetCampaignsTemplateById.
func (mr *MockRepositoryMockRecorder) GetCampaignsTemplateById(ctx, campaignId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignsTemplateById", reflect.TypeOf((*MockRepository)(nil).GetCampaignsTemplateById), ctx, campaignId)
}

// ListCampaign mocks base method.
func (m *MockRepository) ListCampaign(ctx context.Context) ([]entity.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCampaign", ctx)
	ret0, _ := ret[0].([]entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCampaign indicates an expected call of ListCampaign.
func (mr *MockRepositoryMockRecorder) ListCampaign(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCampaign", reflect.TypeOf((*MockRepository)(nil).ListCampaign), ctx)
}

// SaveCampaign mocks base method.
func (m *MockRepository) SaveCampaign(ctx context.Context, campaign *entity.Campaign) (*entity.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCampaign", ctx, campaign)
	ret0, _ := ret[0].(*entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveCampaign indicates an expected call of SaveCampaign.
func (mr *MockRepositoryMockRecorder) SaveCampaign(ctx, campaign interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCampaign", reflect.TypeOf((*MockRepository)(nil).SaveCampaign), ctx, campaign)
}
