// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"github.com/inter-hubly/keeper/internal/domain"
	"github.com/inter-hubly/keeper/internal/domain/kdto"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetVariables mocks base method.
func (m *MockRepository) GetVariables(ctx context.Context) (map[string]domain.SingleVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariables", ctx)
	ret0, _ := ret[0].(map[string]domain.SingleVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariables indicates an expected call of GetVariables.
func (mr *MockRepositoryMockRecorder) GetVariables(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariables", reflect.TypeOf((*MockRepository)(nil).GetVariables), ctx)
}

// SaveManyVariables mocks base method.
func (m *MockRepository) SaveManyVariables(ctx context.Context, variable *domain.Variables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveManyVariables", ctx, variable)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveManyVariables indicates an expected call of SaveManyVariables.
func (mr *MockRepositoryMockRecorder) SaveManyVariables(ctx, variable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveManyVariables", reflect.TypeOf((*MockRepository)(nil).SaveManyVariables), ctx, variable)
}

// SaveVariable mocks base method.
func (m *MockRepository) SaveVariable(ctx context.Context, variable *domain.Variables) (*domain.Variables, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveVariable", ctx, variable)
	ret0, _ := ret[0].(*domain.Variables)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveVariable indicates an expected call of SaveVariable.
func (mr *MockRepositoryMockRecorder) SaveVariable(ctx, variable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVariable", reflect.TypeOf((*MockRepository)(nil).SaveVariable), ctx, variable)
}

// VerifyUserVariables mocks base method.
func (m *MockRepository) VerifyUserVariables(ctx context.Context, variables []kdto.Variable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserVariables", ctx, variables)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUserVariables indicates an expected call of VerifyUserVariables.
func (mr *MockRepositoryMockRecorder) VerifyUserVariables(ctx, variables interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserVariables", reflect.TypeOf((*MockRepository)(nil).VerifyUserVariables), ctx, variables)
}
