// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"github.com/inter-hubly/keeper/internal/domain"
	hctx "github.com/inter-hubly/pilot/hctx"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetTemplateById mocks base method.
func (m *MockRepository) GetTemplateById(ctx context.Context, id string) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateById", ctx, id)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateById indicates an expected call of GetTemplateById.
func (mr *MockRepositoryMockRecorder) GetTemplateById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateById", reflect.TypeOf((*MockRepository)(nil).GetTemplateById), ctx, id)
}

// GetTemplateByIds mocks base method.
func (m *MockRepository) GetTemplateByIds(ctx context.Context, ids []string) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateByIds indicates an expected call of GetTemplateByIds.
func (mr *MockRepositoryMockRecorder) GetTemplateByIds(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateByIds", reflect.TypeOf((*MockRepository)(nil).GetTemplateByIds), ctx, ids)
}

// SaveManyTemplate mocks base method.
func (m *MockRepository) SaveManyTemplate(ctx context.Context, save []domain.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveManyTemplate", ctx, save)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveManyTemplate indicates an expected call of SaveManyTemplate.
func (mr *MockRepositoryMockRecorder) SaveManyTemplate(ctx, save interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveManyTemplate", reflect.TypeOf((*MockRepository)(nil).SaveManyTemplate), ctx, save)
}

// SaveTemplate mocks base method.
func (m *MockRepository) SaveTemplate(ctx context.Context, dto *domain.Template) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTemplate", ctx, dto)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTemplate indicates an expected call of SaveTemplate.
func (mr *MockRepositoryMockRecorder) SaveTemplate(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTemplate", reflect.TypeOf((*MockRepository)(nil).SaveTemplate), ctx, dto)
}

// SearchTemplates mocks base method.
func (m *MockRepository) SearchTemplates(ctx context.Context, logged *hctx.Logged) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTemplates", ctx, logged)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTemplates indicates an expected call of SearchTemplates.
func (mr *MockRepositoryMockRecorder) SearchTemplates(ctx, logged interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTemplates", reflect.TypeOf((*MockRepository)(nil).SearchTemplates), ctx, logged)
}
