// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"github.com/inter-hubly/keeper/internal/domain"
	"github.com/inter-hubly/keeper/internal/domain/kdto"
	hctx "github.com/inter-hubly/pilot/hctx"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CountVariables mocks base method.
func (m *MockService) CountVariables(ctx context.Context, templateId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountVariables", ctx, templateId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountVariables indicates an expected call of CountVariables.
func (mr *MockServiceMockRecorder) CountVariables(ctx, templateId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountVariables", reflect.TypeOf((*MockService)(nil).CountVariables), ctx, templateId)
}

// SaveVariable mocks base method.
func (m *MockService) SaveVariable(ctx context.Context, variables []kdto.Variable, templateId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveVariable", ctx, variables, templateId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveVariable indicates an expected call of SaveVariable.
func (mr *MockServiceMockRecorder) SaveVariable(ctx, variables, templateId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVariable", reflect.TypeOf((*MockService)(nil).SaveVariable), ctx, variables, templateId)
}

// SearchTemplates mocks base method.
func (m *MockService) SearchTemplates(ctx context.Context, user *hctx.Logged) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTemplates", ctx, user)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTemplates indicates an expected call of SearchTemplates.
func (mr *MockServiceMockRecorder) SearchTemplates(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTemplates", reflect.TypeOf((*MockService)(nil).SearchTemplates), ctx, user)
}

// SincronizeWhatsAppTemplate mocks base method.
func (m *MockService) SincronizeWhatsAppTemplate(ctx context.Context, user *hctx.Logged) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SincronizeWhatsAppTemplate", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SincronizeWhatsAppTemplate indicates an expected call of SincronizeWhatsAppTemplate.
func (mr *MockServiceMockRecorder) SincronizeWhatsAppTemplate(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SincronizeWhatsAppTemplate", reflect.TypeOf((*MockService)(nil).SincronizeWhatsAppTemplate), ctx, user)
}
