// Code generated by MockGen. DO NOT EDIT.
// Source: whatsApp.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"github.com/inter-hubly/keeper/internal/domain"
	"github.com/inter-hubly/keeper/internal/domain/kdto"
)

// MockWhatsApp is a mock of WhatsApp interface.
type MockWhatsApp struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppMockRecorder
}

// MockWhatsAppMockRecorder is the mock recorder for MockWhatsApp.
type MockWhatsAppMockRecorder struct {
	mock *MockWhatsApp
}

// NewMockWhatsApp creates a new mock instance.
func NewMockWhatsApp(ctrl *gomock.Controller) *MockWhatsApp {
	mock := &MockWhatsApp{ctrl: ctrl}
	mock.recorder = &MockWhatsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsApp) EXPECT() *MockWhatsAppMockRecorder {
	return m.recorder
}

// CreateTemplate mocks base method.
func (m *MockWhatsApp) CreateTemplate(ctx context.Context, message *domain.Template) (*kdto.WhatsAppTemplateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, message)
	ret0, _ := ret[0].(*kdto.WhatsAppTemplateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockWhatsAppMockRecorder) CreateTemplate(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockWhatsApp)(nil).CreateTemplate), ctx, message)
}

// FindAllTemplate mocks base method.
func (m *MockWhatsApp) FindAllTemplate(ctx context.Context) ([]kdto.WhatsAppMessageTemplateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllTemplate", ctx)
	ret0, _ := ret[0].([]kdto.WhatsAppMessageTemplateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllTemplate indicates an expected call of FindAllTemplate.
func (mr *MockWhatsAppMockRecorder) FindAllTemplate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllTemplate", reflect.TypeOf((*MockWhatsApp)(nil).FindAllTemplate), ctx)
}
