// Code generated by MockGen. DO NOT EDIT.
// Source: campaign.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/inter-hubly/pilot/domain/entity"
)

// MockCampaign is a mock of Campaign interface.
type MockCampaign struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignMockRecorder
}

// MockCampaignMockRecorder is the mock recorder for MockCampaign.
type MockCampaignMockRecorder struct {
	mock *MockCampaign
}

// NewMockCampaign creates a new mock instance.
func NewMockCampaign(ctrl *gomock.Controller) *MockCampaign {
	mock := &MockCampaign{ctrl: ctrl}
	mock.recorder = &MockCampaignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaign) EXPECT() *MockCampaignMockRecorder {
	return m.recorder
}

// GetCampaignById mocks base method.
func (m *MockCampaign) GetCampaignById(ctx context.Context, campaignId string) (*entity.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignById", ctx, campaignId)
	ret0, _ := ret[0].(*entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignById indicates an expected call of GetCampaignById.
func (mr *MockCampaignMockRecorder) GetCampaignById(ctx, campaignId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignById", reflect.TypeOf((*MockCampaign)(nil).GetCampaignById), ctx, campaignId)
}

// GetCampaignsByIds mocks base method.
func (m *MockCampaign) GetCampaignsByIds(ctx context.Context, campaignId ...string) ([]entity.Campaign, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range campaignId {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCampaignsByIds", varargs...)
	ret0, _ := ret[0].([]entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignsByIds indicates an expected call of GetCampaignsByIds.
func (mr *MockCampaignMockRecorder) GetCampaignsByIds(ctx interface{}, campaignId ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, campaignId...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignsByIds", reflect.TypeOf((*MockCampaign)(nil).GetCampaignsByIds), varargs...)
}

// GetCampaignsTemplateById mocks base method.
func (m *MockCampaign) GetCampaignsTemplateById(ctx context.Context, campaignId []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignsTemplateById", ctx, campaignId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignsTemplateById indicates an expected call of GetCampaignsTemplateById.
func (mr *MockCampaignMockRecorder) GetCampaignsTemplateById(ctx, campaignId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignsTemplateById", reflect.TypeOf((*MockCampaign)(nil).GetCampaignsTemplateById), ctx, campaignId)
}

// ListCampaign mocks base method.
func (m *MockCampaign) ListCampaign(ctx context.Context) ([]entity.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCampaign", ctx)
	ret0, _ := ret[0].([]entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCampaign indicates an expected call of ListCampaign.
func (mr *MockCampaignMockRecorder) ListCampaign(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCampaign", reflect.TypeOf((*MockCampaign)(nil).ListCampaign), ctx)
}

// SaveCampaign mocks base method.
func (m *MockCampaign) SaveCampaign(ctx context.Context, campaign *entity.Campaign) (*entity.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCampaign", ctx, campaign)
	ret0, _ := ret[0].(*entity.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveCampaign indicates an expected call of SaveCampaign.
func (mr *MockCampaignMockRecorder) SaveCampaign(ctx, campaign interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCampaign", reflect.TypeOf((*MockCampaign)(nil).SaveCampaign), ctx, campaign)
}
