// Code generated by MockGen. DO NOT EDIT.
// Source: contact.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/inter-hubly/keeper/internal/app/domain"
)

// MockContact is a mock of Contact interface.
type MockContact struct {
	ctrl     *gomock.Controller
	recorder *MockContactMockRecorder
}

// MockContactMockRecorder is the mock recorder for MockContact.
type MockContactMockRecorder struct {
	mock *MockContact
}

// NewMockContact creates a new mock instance.
func NewMockContact(ctrl *gomock.Controller) *MockContact {
	mock := &MockContact{ctrl: ctrl}
	mock.recorder = &MockContactMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContact) EXPECT() *MockContactMockRecorder {
	return m.recorder
}

// FindContacts mocks base method.
func (m *MockContact) FindContacts(ctx context.Context, tenant string) ([]domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindContacts", ctx, tenant)
	ret0, _ := ret[0].([]domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindContacts indicates an expected call of FindContacts.
func (mr *MockContactMockRecorder) FindContacts(ctx, tenant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindContacts", reflect.TypeOf((*MockContact)(nil).FindContacts), ctx, tenant)
}

// SaveContact mocks base method.
func (m *MockContact) SaveContact(ctx context.Context, contact *domain.Contact) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveContact", ctx, contact)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveContact indicates an expected call of SaveContact.
func (mr *MockContactMockRecorder) SaveContact(ctx, contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveContact", reflect.TypeOf((*MockContact)(nil).SaveContact), ctx, contact)
}
