// Code generated by MockGen. DO NOT EDIT.
// Source: message.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/inter-hubly/keeper/internal/app/domain"
	kdto "github.com/inter-hubly/keeper/internal/app/domain/kdto"
)

// MockMessages is a mock of Messages interface.
type MockMessages struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesMockRecorder
}

// MockMessagesMockRecorder is the mock recorder for MockMessages.
type MockMessagesMockRecorder struct {
	mock *MockMessages
}

// NewMockMessages creates a new mock instance.
func NewMockMessages(ctrl *gomock.Controller) *MockMessages {
	mock := &MockMessages{ctrl: ctrl}
	mock.recorder = &MockMessagesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessages) EXPECT() *MockMessagesMockRecorder {
	return m.recorder
}

// GetMessagesByClientId mocks base method.
func (m *MockMessages) GetMessagesByClientId(ctx context.Context, clientId string, searchDto *kdto.Search) (map[string]*domain.Conversations, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesByClientId", ctx, clientId, searchDto)
	ret0, _ := ret[0].(map[string]*domain.Conversations)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessagesByClientId indicates an expected call of GetMessagesByClientId.
func (mr *MockMessagesMockRecorder) GetMessagesByClientId(ctx, clientId, searchDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesByClientId", reflect.TypeOf((*MockMessages)(nil).GetMessagesByClientId), ctx, clientId, searchDto)
}
