// Code generated by MockGen. DO NOT EDIT.
// Source: template.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/inter-hubly/keeper/internal/app/domain"
	hctx "github.com/inter-hubly/pilot/hctx"
)

// MockTemplate is a mock of Template interface.
type MockTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateMockRecorder
}

// MockTemplateMockRecorder is the mock recorder for MockTemplate.
type MockTemplateMockRecorder struct {
	mock *MockTemplate
}

// NewMockTemplate creates a new mock instance.
func NewMockTemplate(ctrl *gomock.Controller) *MockTemplate {
	mock := &MockTemplate{ctrl: ctrl}
	mock.recorder = &MockTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplate) EXPECT() *MockTemplateMockRecorder {
	return m.recorder
}

// GetTemplateById mocks base method.
func (m *MockTemplate) GetTemplateById(ctx context.Context, id string) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateById", ctx, id)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateById indicates an expected call of GetTemplateById.
func (mr *MockTemplateMockRecorder) GetTemplateById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateById", reflect.TypeOf((*MockTemplate)(nil).GetTemplateById), ctx, id)
}

// GetTemplateByIds mocks base method.
func (m *MockTemplate) GetTemplateByIds(ctx context.Context, ids []string) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateByIds indicates an expected call of GetTemplateByIds.
func (mr *MockTemplateMockRecorder) GetTemplateByIds(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateByIds", reflect.TypeOf((*MockTemplate)(nil).GetTemplateByIds), ctx, ids)
}

// SaveTemplate mocks base method.
func (m *MockTemplate) SaveTemplate(ctx context.Context, user *hctx.Logged, dto *domain.Template) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTemplate", ctx, user, dto)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTemplate indicates an expected call of SaveTemplate.
func (mr *MockTemplateMockRecorder) SaveTemplate(ctx, user, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTemplate", reflect.TypeOf((*MockTemplate)(nil).SaveTemplate), ctx, user, dto)
}

// SearchTemplates mocks base method.
func (m *MockTemplate) SearchTemplates(ctx context.Context, logged *hctx.Logged) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTemplates", ctx, logged)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTemplates indicates an expected call of SearchTemplates.
func (mr *MockTemplateMockRecorder) SearchTemplates(ctx, logged interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTemplates", reflect.TypeOf((*MockTemplate)(nil).SearchTemplates), ctx, logged)
}
