// Code generated by MockGen. DO NOT EDIT.
// Source: variables.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/inter-hubly/keeper/internal/app/domain"
)

// MockVariable is a mock of Variable interface.
type MockVariable struct {
	ctrl     *gomock.Controller
	recorder *MockVariableMockRecorder
}

// MockVariableMockRecorder is the mock recorder for MockVariable.
type MockVariableMockRecorder struct {
	mock *MockVariable
}

// NewMockVariable creates a new mock instance.
func NewMockVariable(ctrl *gomock.Controller) *MockVariable {
	mock := &MockVariable{ctrl: ctrl}
	mock.recorder = &MockVariableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVariable) EXPECT() *MockVariableMockRecorder {
	return m.recorder
}

// GetVariables mocks base method.
func (m *MockVariable) GetVariables(ctx context.Context) (map[string]domain.SingleVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariables", ctx)
	ret0, _ := ret[0].(map[string]domain.SingleVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariables indicates an expected call of GetVariables.
func (mr *MockVariableMockRecorder) GetVariables(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariables", reflect.TypeOf((*MockVariable)(nil).GetVariables), ctx)
}

// SaveManyVariables mocks base method.
func (m *MockVariable) SaveManyVariables(ctx context.Context, variable *domain.Variables) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveManyVariables", ctx, variable)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveManyVariables indicates an expected call of SaveManyVariables.
func (mr *MockVariableMockRecorder) SaveManyVariables(ctx, variable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveManyVariables", reflect.TypeOf((*MockVariable)(nil).SaveManyVariables), ctx, variable)
}

// SaveVariable mocks base method.
func (m *MockVariable) SaveVariable(ctx context.Context, variable *domain.Variables) (*domain.Variables, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveVariable", ctx, variable)
	ret0, _ := ret[0].(*domain.Variables)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveVariable indicates an expected call of SaveVariable.
func (mr *MockVariableMockRecorder) SaveVariable(ctx, variable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVariable", reflect.TypeOf((*MockVariable)(nil).SaveVariable), ctx, variable)
}
