// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/inter-hubly/pilot/domain/entity"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetClientByPhoneNumberId mocks base method.
func (m *MockRepository) GetClientByPhoneNumberId(ctx context.Context, clientId string) (*entity.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientByPhoneNumberId", ctx, clientId)
	ret0, _ := ret[0].(*entity.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientByPhoneNumberId indicates an expected call of GetClientByPhoneNumberId.
func (mr *MockRepositoryMockRecorder) GetClientByPhoneNumberId(ctx, clientId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientByPhoneNumberId", reflect.TypeOf((*MockRepository)(nil).GetClientByPhoneNumberId), ctx, clientId)
}

// SaveClient mocks base method.
func (m *MockRepository) SaveClient(ctx context.Context, clientEntity *entity.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveClient", ctx, clientEntity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveClient indicates an expected call of SaveClient.
func (mr *MockRepositoryMockRecorder) SaveClient(ctx, clientEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveClient", reflect.TypeOf((*MockRepository)(nil).SaveClient), ctx, clientEntity)
}
